export const runtime = "nodejs";

import { NextRequest } from "next/server";
import { PDFDocument, rgb } from "pdf-lib";

export async function GET(
  request: NextRequest,
  context: { params: Promise<{ id: string }> }   // ⬅ HARUS Promise!
) {
  const { id } = await context.params; // ⬅ pakai await untuk destructuring

  try {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595, 842]);

    page.drawText("INVOICE", {
      x: 50,
      y: 800,
      size: 28,
      color: rgb(0.1, 0.1, 0.1),
    });

    page.drawText(`Invoice ID: ${id}`, {
      x: 50,
      y: 760,
      size: 18,
      color: rgb(0, 0, 0),
    });

    page.drawText("Generated by KOJE24 • Natural Cold-Pressed Juice", {
      x: 50,
      y: 60,
      size: 12,
      color: rgb(0.4, 0.4, 0.4),
    });

    const pdfBytes = await pdfDoc.save();
    const buffer = Buffer.from(pdfBytes);

    return new Response(buffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename="invoice-${id}.pdf"`,
      },
    });
  } catch (err: any) {
    console.error("PDF error:", err);
    return new Response(
      JSON.stringify({ error: "Failed to generate PDF", detail: err?.message }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}
